### ISSUE TITLE
Iteration Plan for Autumn 2019

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1212]
# Iteration Plan for ~~Summer~~ Autumn 2019

关于~~这个季度~~下个季度的计划被 Ir1d 咕掉了，所以我来简单整理下。

![image](https://user-images.githubusercontent.com/30773956/64026172-cdbcf800-cb70-11e9-8ec9-edd9d6ca4cde.png)

### Changelog

~~目前的计划由@abc1763613206 最终整理于 2019.05.28 。~~  
~~目前的计划由 @Planet6174 整理于 2019.06.27。~~
~~目前的计划由 @StudyingFather 整理于 2019.07.11。~~
~~目前的计划由 @StudyingFather 整理于 2019.07.27。~~
 目前的计划由 @abc1763613206  整理于 2019.08.30。

## **长时间无人处理**

> 简单说就是被审核者/作者咕掉的 PR。        
> 
>它们都被打上了[需要处理 / Need Processing](https://github.com/24OI/OI-wiki/issues?q=is%3Apr+is%3Aopen+label%3A%22%E9%9C%80%E8%A6%81%E5%A4%84%E7%90%86+%2F+Need+Processing%22) 的标签，您可以直接去 Issues 区里自行认领。             

目前已经统计到的待审核/完善的 PR：

- [ ] #1543 Roadmap Chapter1 [**施工中**]

### 出现在 **[Issues](https://github.com/24OI/OI-wiki/issues)** 里的

> 这里记录的都是作者/读者请求添加的内容，统计时发现大部分 Issue 都没有相关人员跟进。   
> 
> 它们都被打上了[内容请求 / Content Request](https://github.com/24OI/OI-wiki/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E5%86%85%E5%AE%B9%E8%AF%B7%E6%B1%82+%2F+Content+Request%22) 的标签，您可以到现场围观，添加内容，或者是催更。

以下目标按序号降序排列。

- [ ] #1435 斯坦纳树
- [ ] #1421 模拟费用流
- [ ] #1369 补充scc相关
- [ ] #1356 #546 **更多的**编辑器内容完善
- [ ] #1327 数学页面分类
- [ ] #1277 二次剩余
- [ ] #1275 Bell Number
- [ ] #1273 min_25筛&洲阁筛
- [ ] #1266 min-max 容斥
- [ ] #1265 wronganswer（OJ 客户端）
- [ ] #1252 DFS序 树形背包 欧拉图 置换群 Catalan数  线段树+离线询问
- [ ] #1246 长链剖分
- [ ] #1242 生成函数
- [ ] #1167 线段树变种
- [ ] #1064 图论（弦图与区间图）
- [ ] #1059 虚树样例部分图解
- [ ] #1041 可追溯化数据化结构
- [ ] #1039 finger tree, 2-3 tree
- [ ] #1023 计算几何相关
- [ ] #1019 左右位移
- [ ] #995 技巧分类
- [ ] #955 指令集操作相关
- [ ] #923 后缀数组应用
- [ ] #890 各阶段知识点建议
- [ ] #886 C++标准/编译器相关
- [ ] #808 合并页面的讨论
- [ ] #698 编辑器页面表述
- [ ] #579 随机化算法合并
- [ ] #577 高精度内容
- [ ] #488 圆方树
- [ ] #486 Trie 内容 & 01字典树
- [ ] #223 树套树
- [ ] #6 rbt，B树，leafy tree，toptree

#### e-maxx 翻译搬运
> @Ir1d 的话：
> e-maxx 的页面较多，但是每个页面工作量不是很大，欢迎感兴趣的同学认领一下力所能及的部分
>
> 有的页面质量不高，也可以留言标注一下跳过 ❤️
>
>请您勇敢地去翻译和改进翻译。虽然我们追求卓越，但我们并不要求您做到十全十美，也请不要担心翻译上犯错——在大部分情况下，git 会记录所有的翻译，因此您不必担心您的失误造成无法挽回的破坏

详见 #148 的统计。

#### 目录内容完善

详见 #187 。

> 注意：#187 内的内容稍有过时，还是建议去认领上面 Issues 里的内容。

## 站务类(非内容补充相关)

- [ ] 新版站点项目(无限咕咕咕)

- [ ] #881 pjax相关
- [ ] #862 中文加粗显示
- [ ] #808 页面合并
- [x] #420 专题栏目
- [ ] #1037 前置知识 **(待讨论)**
- [ ] #178 考虑统一内容格式
- [ ] #1264 考虑每个例题单独一个页面

#### 低优先级

- [ ] #445 征集图标
- [ ] #904 SEO优化相关

## 提上日程的

- 统计低质量版面
- 对内容简单词条进行补充

**Comment by abc1763613206** [comment]
完善前先 reference 下上一个 Plan  https://github.com/24OI/OI-wiki/issues/1065

~~我先咕为敬~~

**Comment by TrisolarisHD** [comment]
@abc1763613206 8 days ago 🤔

**Comment by abc1763613206** [comment]
具体内容已经增修完毕，详见edit后内容。

**Comment by Planet6174** [comment]
Updated

**Comment by StudyingFather** [comment]
计划已更新。

**Comment by StudyingFather** [comment]
Update done.

**Comment by abc1763613206** [comment]
新版的爆改完了（大雾）     
欢迎完善

**Comment by sshwy** [comment]
把一些该勾的勾了

**Comment by abc1763613206** [comment]
@sshwy 整理新计划的话别勾了吧，直接删就是

**Comment by Ir1d** [comment]
开新的吧 orz，这个太长了
