### ISSUE TITLE
Iteration Plan for Autumn 2019

### ISSUE THREAD

**Issue by abc1763613206** [OI-wiki/OI-wiki#1646]
# Iteration Plan for Autumn 2019

关于这一季度的计划~~被 Ir1d 咕掉了~~被 Ir1d 钦定修改了，所以我来简单整理下。

![image](https://user-images.githubusercontent.com/30773956/64026172-cdbcf800-cb70-11e9-8ec9-edd9d6ca4cde.png)

#### 插播一则消息

Ir1d XD+, [20.08.19 13:16]
[转发自频道 OI Wiki News (Ir1d XD+)]
今日，有同学反映在某群中某公司某项目公开征集 wiki 写手，我们打开那个网站之后发现有相当多内容来自 OI Wiki 的开源项目，但是他们在页面上注明自己是作者。经过交涉，对方已经关闭了网站。我们承诺，项目维护组会继续致力于维护大家的利益。同时也希望相关方能遵守我们的开源协议（CC 和 SATA，见 GitHub README）。另外，我们也在和一些企业联系新的合作项目，希望在新学期能帮助 OI Wiki 越办越好。

### Changelog
~~目前的计划由 @abc1763613206 与 @StudyingFather 整理于 2019.08.30。~~  
~~目前的计划由 @StudyingFather 整理于 2019.09.28。~~
目前的计划由 @StudyingFather 整理于 2019.10.28。

## **长时间无人处理**

> 简单说就是被审核者/作者咕掉的 PR。        
> 
>它们都被打上了[需要处理 / Need Processing](https://github.com/OI-wiki/OI-wiki/issues?q=is%3Apr+is%3Aopen+label%3A%22%E9%9C%80%E8%A6%81%E5%A4%84%E7%90%86+%2F+Need+Processing%22) 的标签，您可以直接去 Issues 区里自行认领。             

#### 高优先级
- [ ] #1543 Roadmap Chapter1 
#### 其他
- [x] #1820 #1822 #1823 #1824 #1827 修改目录
- [x] #1672 出题专题

### 内容需增修

- [x] #1728 平衡树内容更新
- [x] #1641 增加长链剖分内容
- [x] #1621 增加 Notepad++ 内容
- [x] #1754 #1605 修正“主定理”错误+补充

### 出现在 **[Issues](https://github.com/OI-wiki/OI-wiki/issues)** 里的

> 这里记录的都是作者/读者请求添加的内容，统计时发现大部分 Issue 都没有相关人员跟进。   
> 
> 它们都被打上了[内容请求 / Content Request](https://github.com/OI-wiki/OI-wiki/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E5%86%85%E5%AE%B9%E8%AF%B7%E6%B1%82+%2F+Content+Request%22) 的标签，您可以到现场围观，添加内容，或者是催更。

以下目标按序号降序排列。

- [x] #1788 Johnson 全源最短路径算法
- [ ] #1766 mingw_w64/gcc 安装指南
- [ ] #1765 tarjan 的最小树形图算法
- [ ] #1764 Minimum Diameter Spanning Tree
- [ ] #1732 GarsiaWachs 算法
- [x] #1729 #923 对后缀数组内容的补充与更新
- [ ] #1709 多维差分
- [x] #1682 跳表
- [ ] #1674 Git 使用指南
- [x] #1613 单调队列优化多重背包
- [ ] #1608 #577 高精度内容
- [ ] #1596 Schreier–Sims 算法
- [x] #1508 自适应辛普森法
- [x] #1504 zkw 费用流
- [x] #1495 命令行，gdb
- [ ] #1481 #6 rbt，B树，leafy tree，toptree
- [x] #1435 斯坦纳树
- [ ] #1421 模拟费用流
- [x] #1369 补充scc相关
- [x] #1356 #546 **更多的**编辑器内容完善
- [x] #1327 数学页面分类
- [x] #1277 二次剩余
- [x] #1275 Bell Number
- [ ] #1273 min_25筛&洲阁筛
- [x] #1266 min-max 容斥
- [ ] #1252 DFS序 树形背包 欧拉图 置换群 Catalan数  线段树+离线询问
- [x] #1246 长链剖分
- [x] #1242 生成函数
- [ ] #1167 线段树变种
- [x] #1064 图论（弦图与区间图）
- [x] #1059 虚树样例部分图解
- [ ] #1041 可追溯化数据化结构
- [ ] #1039 finger tree, 2-3 tree
- [ ] #1023 计算几何相关
- [x] #1019 左右位移
- [ ] #995 技巧分类
- [ ] #955 指令集操作相关
- [ ] #890 各阶段知识点建议
- [ ] #886 C++标准/编译器相关
- [x] #808 合并页面的讨论
- [ ] #698 编辑器页面表述
- [ ] #579 随机化算法合并
- [ ] #488 圆方树
- [x] #486 Trie 内容 & 01字典树
- [ ] #223 树套树

#### e-maxx 翻译搬运
> @Ir1d 的话：
> e-maxx 的页面较多，但是每个页面工作量不是很大，欢迎感兴趣的同学认领一下力所能及的部分
>
> 有的页面质量不高，也可以留言标注一下跳过 ❤️
>
>请您勇敢地去翻译和改进翻译。虽然我们追求卓越，但我们并不要求您做到十全十美，也请不要担心翻译上犯错——在大部分情况下，git 会记录所有的翻译，因此您不必担心您的失误造成无法挽回的破坏

详见 #148 的统计。

#### 目录内容完善

详见 #187 。

> 注意：#187 内的内容稍有过时，还是建议去认领上面 Issues 里的内容。

## 站务类(非内容补充相关)

- [ ] 新版站点项目(无限咕咕咕)
   - 在等 <https://v2.docusaurus.io>
- [ ] #881 pjax相关
- [x] #862 中文加粗显示
- [x] #808 页面合并
- [x] #1037 前置知识 **(待讨论)**
- [ ] #178 考虑统一内容格式
- [ ] #1264 考虑每个例题单独一个页面

#### 低优先级

- [ ] #445 征集图标
- [ ] #904 SEO优化相关

## 提上日程的

- 统计低质量版面
- 对内容简单词条进行补充

**Comment by StudyingFather** [comment]
添加了一些最近的内容请求内容，顺带 pin issue 😄

**Comment by AngelKitty** [comment]
支持

**Comment by StudyingFather** [comment]
计划已更新。

添加了一些长期咕咕咕的 PR 和最近的内容请求供各位催更（bushi

**Comment by ouuan** [comment]
供各位咕咕（指正）

~~我的两个计划被列上了下辈子填清单！~~

**Comment by abc1763613206** [comment]
> 供各位咕咕（指正）
> 
> ~我的两个计划被列上了下辈子填清单！~

@ouuan 快去结束一下出题专题啊，拖太久了（

**Comment by StudyingFather** [comment]
计划又双叒叕更新了.webp

欢迎大家继续围观，或者是~~催更~~继续咕。

**Comment by abc1763613206** [comment]
winter 的该准备下了

**Comment by H-J-Granger** [comment]
所以……
为啥Winter 2019都过了这个issue还pin在上面

**Comment by StudyingFather** [comment]
see #2589.
