### ISSUE TITLE
Iteration Plan for Autumn 2020

### ISSUE THREAD

**Issue by StudyingFather** [OI-wiki/OI-wiki#2589]
# Iteration Plan for Autumn 2020

关于这一季度的计划~~被 Ir1d 咕掉了~~被 Ir1d 钦定修改了，所以我来简单整理下。

![image](https://user-images.githubusercontent.com/30773956/64026172-cdbcf800-cb70-11e9-8ec9-edd9d6ca4cde.png)

### Changelog
目前的计划由 @StudyingFather 整理于 2020.08.24。

## **长时间无人处理**

> 简单说就是被审核者/作者咕掉的 PR。        
> 
>它们都被打上了[需要处理 / Need Processing](https://github.com/OI-wiki/OI-wiki/issues?q=is%3Apr+is%3Aopen+label%3A%22%E9%9C%80%E8%A6%81%E5%A4%84%E7%90%86+%2F+Need+Processing%22) 的标签，您可以直接去 Issues 区里自行认领。

### 内容需增修

- [x] #2218 tri-func
- [x] #2148 Pascal 转 C++ 中引用相关内容
- [x] #2069 埃氏筛法
- [ ] #1920 指针内容

### 出现在 **[Issues](https://github.com/OI-wiki/OI-wiki/issues)** 里的

> 这里记录的都是作者/读者请求添加的内容，统计时发现大部分 Issue 都没有相关人员跟进。   
> 
> 它们都被打上了[内容请求 / Content Request](https://github.com/OI-wiki/OI-wiki/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E5%86%85%E5%AE%B9%E8%AF%B7%E6%B1%82+%2F+Content+Request%22) 的标签，您可以到现场围观，添加内容，或者是催更。

以下目标按序号降序排列。

- [x] #2588 同余最短路
- [ ] #2574 timsort
- [ ] #2440 数位 DP
- [x] #2392 高精度取余
- [ ] #2388 一般图最大权匹配
- [x] #2375 Pollard-Rho
- [ ] #2367 STL 解决实际问题
- [ ] #2366 最大费用可行流
- [ ] #2354 线段树合并&分裂
- [ ] #2188 二次离线莫队&回滚莫队
- [ ] #2168 动态图连通性问题
- [ ] #2141 多项式求逆精度相关
- [ ] #2063 后缀树&广义后缀自动机
- [ ] #2038 #1860 调整 DP 优化分类&添加 DP 状态说明
- [ ] #2007 因为换行符不同导致的错误
- [ ] #1939 可持久化数据结构
- [ ] #1881 Sperner 定理
- [ ] #1852 完善博弈论页面
- [x] #1843 完善关联式容器
- [ ] #1842 杨表
- [ ] #1836 undefined behavior
- [x] #1792 锦标赛排序
- [ ] #1791 Meissel-Lehmer 算法
- [ ] #1766 mingw_w64/gcc 安装指南
- [x] #1765 tarjan 的最小树形图算法
- [x] #1764 Minimum Diameter Spanning Tree
- [ ] #1732 GarsiaWachs 算法
- [ ] #1709 多维差分
- [ ] #1674 Git 使用指南
- [ ] #1596 Schreier–Sims 算法
- [ ] #1481 #6 rbt，B树，leafy tree，toptree
- [ ] #1421 模拟费用流
- [ ] #1273 min_25筛&洲阁筛
- [ ] #1252 DFS序 树形背包 欧拉图 置换群 Catalan数  线段树+离线询问
- [ ] #1167 线段树变种
- [ ] #1041 可追溯化数据化结构
- [ ] #1039 finger tree, 2-3 tree
- [ ] #1023 计算几何相关
- [ ] #995 技巧分类
- [ ] #955 指令集操作相关
- [ ] #890 各阶段知识点建议
- [ ] #886 C++标准/编译器相关
- [ ] #698 编辑器页面表述
- [x] #579 随机化算法合并
- [x] #488 圆方树
- [ ] #223 树套树

#### e-maxx 翻译搬运
> @Ir1d 的话：
> e-maxx 的页面较多，但是每个页面工作量不是很大，欢迎感兴趣的同学认领一下力所能及的部分
>
> 有的页面质量不高，也可以留言标注一下跳过 ❤️
>
>请您勇敢地去翻译和改进翻译。虽然我们追求卓越，但我们并不要求您做到十全十美，也请不要担心翻译上犯错——在大部分情况下，git 会记录所有的翻译，因此您不必担心您的失误造成无法挽回的破坏

详见 #148 的统计。

#### 目录内容完善

详见 #187 。

> 注意：#187 内的内容稍有过时，还是建议去认领上面 Issues 里的内容。

## 站务类(非内容补充相关)

- [ ] #1956 新版站点项目
- [ ] #1899 i18n
  - <https://github.com/OI-wiki/i18n>
- [ ] #1895 在新标签页打开站外链接
- [ ] #1264 考虑每个例题单独一个页面
- [ ] #881 pjax相关
- [ ] #178 考虑统一内容格式

### 低优先级

- [x] #904 SEO优化相关
- [ ] #445 征集图标

## 提上日程的

- 统计低质量版面
- 对内容简单词条进行补充
