### ISSUE TITLE
Iteration Plan for Spring 2021

### ISSUE THREAD

**Issue by abc1763613206** [OI-wiki/OI-wiki#2976]
# Iteration Plan for Spring 2021

又是一年春将至，苦写计划盼君识。

![image](https://user-images.githubusercontent.com/30773956/107211760-f5d8a800-6a40-11eb-82a3-d34ff3957883.png)

![image](https://user-images.githubusercontent.com/30773956/64026172-cdbcf800-cb70-11e9-8ec9-edd9d6ca4cde.png)

### Changelog
- 计划由 @abc1763613206 整理于 2021.02.08。
- 2/24：增加工作量较大分类； #3016

## 工作量较大
此部分可能成为 Summer2021 项目
- [ ] #3016 

## **长时间无人处理**

> 简单说就是被审核者/作者咕掉的 PR。        
> 
> 它们都被打上了 [Need Processing / 需要处理](https://github.com/OI-wiki/OI-wiki/issues?q=is%3Aopen+sort%3Aupdated-desc+label%3A%22Need+Processing+%2F+%E9%9C%80%E8%A6%81%E5%A4%84%E7%90%86%22) 的标签，您可以直接去 Issues 区里自行认领。

> 一般只有未处理的 PR 会出现在这里。

### 内容需增修
- [x] #2857 CP Editor
- [x] #2838 平面图修订
- [x] #2824 Sublime Text 3
- [ ] #2687 整数分解
- [ ] #2685 Rabin-Karp 算法
- [ ] #2660 combination(排列组合)
- [x] #2634 Garner 算法
- [x] #2627 Git 
- [ ] #2531 Counting labeled graph(计数标记图)
- [x] #2514 all-submasks(枚举给定掩码的所有子掩码)
- [ ] #1920 指针内容

### 内容冲突
- [ ] #2725 #2724 为斜率优化式子增加细节

### 出现在 **[Issues](https://github.com/OI-wiki/OI-wiki/issues)** 里的

> 这里记录的都是作者/读者请求添加的内容，统计时发现大部分 Issue 都没有相关人员跟进。   
> 
> 它们都被打上了[Content Request / 内容请求](https://github.com/OI-wiki/OI-wiki/labels/Content%20Request%20%2F%20%E5%86%85%E5%AE%B9%E8%AF%B7%E6%B1%82) 的标签，您可以到现场围观，添加内容，或者是催更。

> 出于维护困难原因，这里仅列举已统计的部分，更多内容还请链接查看。

以下目标按序号降序排列。
- [x] #2908 欧拉数
- [x] #2889 STL 优先队列
- [ ] #2875 图上随机游走
- [x] #2858 后缀平衡树
- [ ] #2574 timsort
- [ ] #2440 数位 DP
- [ ] #2388 一般图最大权匹配
- [ ] #2367 STL 解决实际问题
- [ ] #2366 最大费用可行流
- [ ] #2354 线段树合并&分裂
- [ ] #2188 二次离线莫队&回滚莫队
- [ ] #2168 动态图连通性问题
- [x] #2141 多项式求逆精度相关
- [ ] #2063 后缀树&广义后缀自动机
- [ ] #2038 #1860 调整 DP 优化分类&添加 DP 状态说明
- [x] #2007 因为换行符不同导致的错误
- [ ] #1939 可持久化数据结构
- [x] #1881 Sperner 定理
- [ ] #1852 完善博弈论页面
- [ ] #1842 杨表
- [ ] #1836 undefined behavior
- [x] #1791 Meissel-Lehmer 算法
- [ ] #1766 mingw_w64/gcc 安装指南
- [ ] #1732 GarsiaWachs 算法
- [ ] #1709 多维差分
- [x] #1674 Git 使用指南
- [ ] #1596 Schreier–Sims 算法
- [ ] #1481 #6 rbt，B树，leafy tree，toptree
- [ ] #1421 模拟费用流
- [x] #1273 min_25筛&洲阁筛
- [ ] #1252 DFS序 树形背包 欧拉图 置换群 Catalan数  线段树+离线询问
- [ ] #1167 线段树变种
- [ ] #1041 可追溯化数据化结构
- [ ] #1039 finger tree, 2-3 tree
- [ ] #1023 计算几何相关
- [ ] #995 技巧分类
- [ ] #955 指令集操作相关
- [ ] #890 各阶段知识点建议
- [ ] #886 C++标准/编译器相关
- [ ] #698 编辑器页面表述
- [ ] #223 树套树

#### e-maxx 翻译搬运
> @Ir1d 的话：
> e-maxx 的页面较多，但是每个页面工作量不是很大，欢迎感兴趣的同学认领一下力所能及的部分
>
> 有的页面质量不高，也可以留言标注一下跳过 ❤️
>
>请您勇敢地去翻译和改进翻译。虽然我们追求卓越，但我们并不要求您做到十全十美，也请不要担心翻译上犯错——在大部分情况下，git 会记录所有的翻译，因此您不必担心您的失误造成无法挽回的破坏。

详见 #148 的统计。

#### 目录内容完善

详见 #187 。

> 注意：#187 内的内容稍有过时，还是建议去认领上面 Issues 里的内容。

## 站务类(非内容补充相关)

- [ ] #1956 **新版站点项目**
- [ ] #1899 i18n
  - <https://github.com/OI-wiki/i18n>
- [ ] #1895 在新标签页打开站外链接
- [ ] #1264 考虑每个例题单独一个页面
- [ ] #178 考虑统一内容格式

### 低优先级

- [ ] #445 征集图标

## One More Thing
2020年，OI Wiki 参与了[**开源软件供应链点亮计划——暑期2020**](https://github.com/OI-wiki/OI-wiki/wiki/Open-Source-Promotion-Plan---Summer-2020)，取得了丰硕的成果。（其中[导出为 PDF](https://github.com/OI-wiki/OI-Wiki-export/releases) 功能已经实现，欢迎下载体验）

~~2021年的计划还在筹备之中，敬请期待，欢迎提出项目。~~

upd： https://github.com/OI-wiki/OI-wiki/wiki/Open-Source-Promotion-Plan-Summer-2021

**Comment by abc1763613206** [comment]
closes #2589

**Comment by H-J-Granger** [comment]
close #1881

**Comment by swift-zym** [comment]
close #2007

**Comment by StudyingFather** [comment]
see #3272.
