### ISSUE TITLE
Iteration Plan for Spring 2022

### ISSUE THREAD

**Issue by ksyx** [OI-wiki/OI-wiki#3757]
# Iteration Plan for Spring 2022

![image](https://user-images.githubusercontent.com/30773956/107211760-f5d8a800-6a40-11eb-82a3-d34ff3957883.png)

![image](https://user-images.githubusercontent.com/30773956/64026172-cdbcf800-cb70-11e9-8ec9-edd9d6ca4cde.png)

咱尽量分类和优化 appearance 了，方便各位捡自己能做的来 awa

## Changelog
Add RFCs and minor updates on 2022/1/30
Initial version by @ksyx on 2022/1/22

## Pull Requests

> 简单说就是被审核者/作者咕掉的 PR，您可以尝试帮助补充和审阅。

### 需要 Review
> 这其中一部分内容在 PR 尾部没有看到需要修改的地方
- [x] DP Refactor [ #2912 ]
- [x] 贪心复杂度 [ #3219 ]
- [x] 长链剖分 Refactor [ #3095 ]
- [x] 多项式逆元 [ #3928 ]
#### 需要讨论
- [x] AC 自动机部分改用 mathtt [ #3344 ]
### 需要增修内容
- [x] 立体几何 [ #3032 ]
- [x] Python 速成 [ #3228 ]
#### Review 建议无响应
- [x] 转换到 WSL2 [ #3055 ]
- [x] 枚举复杂度 [ #3192 ]
- [x] Fix gitment 171 [ #3109 ]
- [x] Splay time complexity [ #3733 ] (14 days)
##### Easy?
- [x] 拆分代码 [ #3459 ]
- [x] Author [ #3675 ]
## Issues
> 以下记录的都是作者/读者请求添加的内容，统计时发现大部分 Issue 都没有相关人员跟进。   
> 
> 它们许多都被打上了[Content Request / 内容请求](https://github.com/OI-wiki/OI-wiki/labels/Content%20Request%20%2F%20%E5%86%85%E5%AE%B9%E8%AF%B7%E6%B1%82) 的标签，您可以到现场围观，添加内容，或者是催更。

### 内容
> Inherited from Summer 2021
#### Easy?
- [x] 后缀数组中的求height数组代码少了一行 [ #3356 ]
- [x] 哈希表页面表述待补充 [ #2205 ]
- [x] Lambda [ #1932 ]
- [x] 运算符优先级表 [ #3571 ]
##### DP
> 请参考 PR DP Refactor [ #2912 ]
- [x] 数位 DP [ #2440 ]
- [x] 背包 DP 第 K 优解 [ #3204 ]
- [x] 补充插头 DP 页面的部分题目题意 [ #2993 ]
- 调整 DP 优化分类 & 添加 DP 状态说明
  - [x] #2038
  - [ ] #1860
##### 线段树
- [x] 线段树合并&分裂 [ #2354 ]
- [ ] 线段树变种 [ #1167 ]
- [x] 线段树+离线询问 [ 部分 #1252 ]
##### 数据结构
> 可能会混入奇怪的东西
- [ ] 可持久化数据结构 [ #1939 ]
  - 可持久化{动机(?)，栈，队列，双向队列，数组}
- [ ] 可追溯化数据结构 [ #1041 ]
##### 图
- [ ] 图上随机游走 [ #2875 ]
- [ ] 一般图最大权匹配 [ #2388 ]
- [ ] 最大费用可行流 [ #2366 ]
- [ ] 动态图连通性问题 [ #2168 ]
- [ ] 模拟费用流 [ #1421 ]
- [x] 支配树 [ #3438 ]
- [ ] 树套树 [ #223 ]
- [ ] rbt，B树，leafy tree，toptree [ #6 ]
- [x] 后缀树 [ #2063 ]
##### 未分类
> 把类似的东西归类在一起了
- [ ] Hackenbush Game [ #3224 ]
- [x] timsort [ #2574 ]
- [x] STL 解决实际问题 [ #2367 ]
- [ ] 完善博弈论页面 [ #1852 ]
- [ ] 多维差分 [ #1709 ]
- [ ] Math roadmap [ #2812 ]
- [x] DFS序 树形背包 欧拉图 置换群 Catalan数 [ 部分 #1252 ]
- [ ] 二次离线莫队&回滚莫队 [ #2188 ]
- [ ] 计算几何相关 [ #1023 ]
- [ ] 补充凸包页面内容 [ #3261 ]
#### 编译器/环境
- [x] undefined behavior [ #1836 ]
- [x] mingw_w64/gcc 安装指南 [ #1766 ]
- [ ] C++ 标准/编译器相关 [ #886 ]
- [ ] 编辑器页面表述 [ #698 ]
#### 学习指导
- [ ] 技巧分类 [ #995 ]
- [ ] 各阶段知识点建议 [ #890 ]
### 需要讨论/更新进展
- [ ] 语言基础 [ #1831 ]
- [x] 编译入门知识 [ #3151 ]
- [ ] 统一内容格式 [ #178 ]
### 魔法
- [ ] Intrinsics [ #955 ]
### 内容增强
- [ ] 对常用数据结构增加动画演示的功能 [ #3221 ]

#### e-maxx 翻译搬运
> @Ir1d 的话：
> e-maxx 的页面较多，但是每个页面工作量不是很大，欢迎感兴趣的同学认领一下力所能及的部分
>
> 有的页面质量不高，也可以留言标注一下跳过 ❤️
>
>请您勇敢地去翻译和改进翻译。虽然我们追求卓越，但我们并不要求您做到十全十美，也请不要担心翻译上犯错——在大部分情况下，git 会记录所有的翻译，因此您不必担心您的失误造成无法挽回的破坏。

详见 #148 的统计。

#### 目录内容完善

详见 #187 。

> 注意：#187 内的内容稍有过时，还是建议去认领上面 Issues 里的内容。

#### RFCs
> Request for Comments，欢迎发表你的意见
- [ ] 维护者寄语 [ #3649 ]
- [ ] 题目储存方式 [ #3518 ]
- [ ] SVG 节点和边的 stylesheet [ #3443 ]
- [ ] 编辑及审阅规范 changelog [ #3701 ]

#### 格式相关
- Clang-format
  - [ ] Clang-Format 上游 fixes [ #2242 ]
  - [x] 格式化代码时插入空行 [ #3717 ]
- [ ] 格式化数学公式 [ #3718 ]
- [ ] 格式手册对 APNG 的介绍问题 [ #3573 ]
- [ ] 改用 mathtt可能可以补充格式手册 [ #4374 ]

#### 其它
- [ ] 拼音搜索 [ #3145 ]
- [x] Status Page [ #3200 ]

### 其他
- [ ] 征集图标 [ #445 ]

**Comment by Great-designer** [comment]
这个应该可以从置顶上面换下来了 #5135

**Comment by Tiphereth-A** [comment]
close via #5135
