### ISSUE TITLE
根据「OI Wiki 不是什么」征集需要修改的页面列表

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#5045]
由于历史原因，OI Wiki 内的部分页面内容不符合 [项目方针：OI Wiki 不是什么](https://oi-wiki.org/intro/what-oi-wiki-is-not/)，为了方便修改页面，现在需要整理一份不符合该方针的页面列表。

若有需要补充至本列表的页面链接，欢迎各位直接编辑或在本 issue 下留言 ❤️

- [ ] [/docs/string/bm.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/string/bm.md)

    具体内容：参见 https://github.com/OI-wiki/OI-wiki/issues/5045#issuecomment-1751944626

- [ ] [/docs/string/ac-automaton.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/string/ac-automaton.md)

    具体内容：参见 https://github.com/OI-wiki/OI-wiki/issues/5045#issuecomment-1759241741

- [x] [/docs/lang/csl/bitset.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/lang/csl/bitset.md)

    具体内容：#5201

- [x] [/docs/tools/editor/vim.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/tools/editor/vim.md)

    具体内容：#698

- [x] [/docs/graph/dsu-on-tree.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/graph/dsu-on-tree.md) (#5052)

    具体内容：「运用」一节中存在个人博客式内容（……吊着打）

- [x] [/docs/graph/prufer.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/graph/prufer.md) (#5052)

    具体内容：
    
    - 开篇存在个人博客式内容（本文**我**按照大多数人的习惯……）
    - 「引入」一节中存在个人博客式内容（显然你不会想不开……）
    - 「线性构造」一节中存在个人博客式内容（翻译到这突然就……）
    - 「线性时间重建树」一节中存在个人博客式内容（原文讲得也很略所以我也不细讲啦）

- [x] [/docs/graph/tree-divide.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/graph/tree-divide.md) (#5052)

    具体内容：「边分治」一节中存在个人博客式内容（ちょっとまって，这不行吧……）

- [x] [/docs/math/bignum.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/math/bignum.md) (#5052)

    具体内容：「除法」一节中存在个人博客式内容（也就是竖～～～～竖式长除法啦！）

- [x] [/docs/math/complex.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/math/complex.md) (#5071)

    具体内容：「多值函数」、「复对数函数」、「一般指数函数」、「一般幂函数与复数乘方开方」等节中有关复变函数的内容目前没有足够的证据证明其在编程竞赛中存在一定的应用。

- [x] [/docs/math/number-theory/discrete-logarithm.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/math/number-theory/discrete-logarithm.md) (#5020)

    具体内容：「多值函数」 一节的复变函数内容目前没有足够的证据证明其在编程竞赛中存在一定的应用。

- [x] [/docs/math/number-theory/prime.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/math/number-theory/prime.md) (#5052)

    具体内容：「引入」一节中存在个人博客式内容（**我**所理解的反素数定义）

- [x] [/docs/math/poly/ntt.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/math/poly/ntt.md) (#5067)

    具体内容：复数论变换（CNTT）目前没有足够的证据证明其在编程竞赛中存在一定的应用。

- [x] [/docs/misc/hill-climbing.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/misc/hill-climbing.md) (#5052)

    具体内容：「简介」一节存在个人博客式内容（……我不三分了 JOJO！）

- [x] [/docs/misc/random.md](https://github.com/OI-wiki/OI-wiki/blob/master/docs/misc/random.md) (#5053)

    具体内容：「随机数分布」一节中的表应直接引用 <https://zh.cppreference.com/w/cpp/numeric/random#.E9.9A.8F.E6.9C.BA.E6.95.B0.E5.88.86.E5.B8.83>。另外原内容的表中部分名词名称是错误的，如 $\gamma$ 分布，$x^2$ 分布。

**Comment by Great-designer** [comment]
如果可以避过“多值函数”、“复对数函数”、“一般指数函数”、“一般幂函数与复数乘方开方”等节的讨论，而仍然可以讲清楚下文的“单位根”和“本原单位根”，而不造成歧义，那自然是极好的。

相关内容的取舍，以及谋篇布局的设计，需要仔细思考。

**Comment by Great-designer** [comment]
记录一下 #5053 提到的

其中有用的分布，可以在讲解概率的页面提一提。

比如，如何生成(0,1)均匀分布的浮点数，如果只用旧版本的C写（而不是C++11附带的东西）会变得出奇困难。简单提一下常见分布的简便写法也是有用的。

**Comment by alphagocc** [comment]
应当注意到现在没有不使用 C++11 及以上标准的比赛

**Comment by r-value** [comment]
> 记录一下 #5053 提到的
> 
> 其中有用的分布，可以在讲解概率的页面提一提。
> 
> 比如，如何生成(0,1)均匀分布的浮点数，如果只用旧版本的C写（而不是C++11附带的东西）会变得出奇困难。简单提一下常见分布的简便写法也是有用的。

应当注意本 Issue 是 "征集需要修改的页面", 对已经修改合规的页面/实际修改的意见应当另起一个话题而不是在这里 off-topic

**Comment by Tiphereth-A** [comment]
> 如果可以避过“多值函数”、“复对数函数”、“一般指数函数”、“一般幂函数与复数乘方开方”等节的讨论，而仍然可以讲清楚下文的“单位根”和“本原单位根”，而不造成歧义，那自然是极好的。

我觉得要讲清楚单位根和本原单位根只需要辐角和复指数函数就够了，因为是「单位」根，所以不涉及一般复数的幂次问题。

**Comment by Great-designer** [comment]
记录一下 #5090 提出的《符号化方法》一文语言叙述层面较为抽象的问题。

**Comment by Tiphereth-A** [comment]
> 记录一下 #5090 提出的《符号化方法》一文语言叙述层面较为抽象的问题。

off topic，页面叙述较为抽象与 [项目方针：OI Wiki 不是什么](https://oi-wiki.org/intro/what-oi-wiki-is-not/) 无矛盾关系。应另开新 issue 而不是在这里讨论。

**Comment by ImpleLee** [comment]
Boyer–Moore 算法的页面我觉得违反得还挺明显的……

**Comment by Tiphereth-A** [comment]
> Boyer–Moore 算法的页面我觉得违反得还挺明显的……

Hi, 可以具体说一下哪些部分违反了项目方针嘛 ❤️

**Comment by LeoJacob** [comment]
> Boyer–Moore 算法的页面我觉得违反得还挺明显的……

补充一下个人认为违反的点。

https://oi.wiki/string/bm/ 从 [delta2 构建细节](https://oi.wiki/string/bm/#delta_2-%E6%9E%84%E5%BB%BA%E7%BB%86%E8%8A%82) 开始带有强烈的个人博客风格，可能违反“OI Wiki 不是个人博客”的项目方针。

此外，这篇内容的叙述上使用 Rust 语言，和竞赛无关，也与流行的语言无关。在 OI Wiki 的算法知识页出现这种语言看起来十分令人困惑。

**Comment by ImpleLee** [comment]
我想指出的是这种个人博客风格不适合oi wiki，关于rust的部分我倒觉得都还行……

**Comment by Great-designer** [comment]
> https://oi.wiki/string/bm/ 从 [delta2 构建细节](https://oi.wiki/string/bm/#delta_2-%E6%9E%84%E5%BB%BA%E7%BB%86%E8%8A%82) 开始带有强烈的个人博客风格，可能违反“OI Wiki 不是个人博客”的项目方针。
> 

引用部分原文：

> 而构造 delta_2 的具体实现的讨论出现在 1977 年 6 月 Knuth、Morris、Pratt 在SIAM Journal on Computing上正式联合发表的 KMP 算法的论文[2](https://oi-wiki.org/string/bm/#fn:kmp)里（这篇论文是个宝藏，除了 KMP，其中还提及了若干字符串搜索的算法构想和介绍，其中就包括了本文介绍的 BM 算法），**听起来有点儿魔幻，嗯哼？**这就不得不稍微介绍一点历史细节了：

> 1969 年夏天 Morris 为某个大型机编写文本编辑器时利用有限自动机的理论发明了等价于 KMP 算法的字符串匹配算法，而他的算法由于过于复杂，被不理解他算法的同事当做 bug 修改得一团糟，**哈哈。**

我认为这里确实有“个人博客风格”，不当的语气词汇应当移除。

> 此外，这篇内容的叙述上使用 Rust 语言，和竞赛无关，也与流行的语言无关。在 OI Wiki 的算法知识页出现这种语言看起来十分令人困惑。

Rust 语言本身没有问题，这里的问题似乎是“缺失C++/Java/python等较为常用的语言”，需要补充。

**Comment by immccn123** [comment]
https://oi-wiki.org/string/ac-automaton/ AC 自动机一节 感觉文风还是很偏向博客的 包括「笔者」一类的字眼 应该是需要改进的吧

贴一段

> 而这篇文章就是为你们打造的。笔者在自学 AC 自动机后花费两天时间制作若干的 gif，呈现出一个相对直观的自动机形态。尽管这个图似乎不太可读，但这绝对是在作者自学的时侯，画得最认真的 gif 了。另外有些小伙伴问这个 gif 拿什么画的。笔者用 Windows 画图软件制作。

**Comment by Great-designer** [comment]
> https://oi-wiki.org/string/ac-automaton/ AC 自动机一节 感觉文风还是很偏向博客的 包括「笔者」一类的字眼 应该是需要改进的吧

“笔者”这类第一人称用词确实有可能需要普遍查找并更正为第三人称

**Comment by Great-designer** [comment]
根据评论区，有人认为现有数论最后一篇“佩尔方程”书写过难，并且存在不适合OI领域的可能。

可以进行：
A. 补充完善
B. 调整更改
C. 部分删改
D. 整体删除

**Comment by Enter-tainer** [comment]
> 感觉作者没有用一个严肃的态度对待这个页面

这句话就没必要发了。除了会引起冲突之外好像没有别的用处。特别是你还专门cc了原来的作者。。

**Comment by Tiphereth-A** [comment]
B 树和 B+ 树在 OI 中没有足够的应用价值，我觉得应该考虑删除

另外 2-3-4 树和 2-3 树的理论价值大于应用价值，也许可以考虑分别和红黑树以及左偏红黑树合并

related: #5736
