### ISSUE TITLE
Iteration Plan for 2023

### ISSUE THREAD

**Issue by yuhuoji** [OI-wiki/OI-wiki#5135]
# Iteration Plan

> 对目前 issue 进行了分类，欢迎大家搞搞自己擅长的😚
> 有问题或新进度可以直接修改本 issue。

## Pull Requests

> 在统计的过程中发现有些 pr 开了之后作者没有持续跟进，最后废弃...这部分可以考虑统计下用作后续参考？
> 这部分没有全罗列上来。

- [ ] 根号分治 [ #5012 ]

---

## Issues

> 以下是作者/读者请求添加的内容，目前大部分 Issue 都没有相关人员持续跟进。
>
> 它们许多都被打上了 [Content Request / 内容请求](https://github.com/OI-wiki/OI-wiki/labels/Content%20Request%20%2F%20%E5%86%85%E5%AE%B9%E8%AF%B7%E6%B1%82) 的标签，欢迎到现场围观，添加内容和参考资料，或者是催更。
>
> 欢迎持续更新这部分内容，并讨论删除不适合OI-Wiki引入的页面，依据 [OI Wiki 不是什么](https://oi-wiki.org/intro/what-oi-wiki-is-not/)。

### 不知道放哪

- [x] [ #4675 ]

---

### 内容

> Inherited from Iteration Plan for Spring 2022

##### 语言基础

- [ ] [ #4480 ]

##### 算法基础

- [ ] 二分查找，有人开过 pr 然后寄了 [ #4552 ]
- [ ] 高维前缀和 [ #4151 ]
- [ ] [ #5536 ]

##### 搜索

- [x] [ #4827 ]

##### DP

- [ ] [ #1860 ]

##### 字符串

- [ ] [ #4790 ]
- [ ] [ #4268 ]
- [ ] [ #3243 ]

##### 数学

- [ ] [ #5011 ]
- 枚举相关，好像 duplicated
  - [x] [ #5097 ]
  - [x] [ #4991 ]
- [ ] [ #4842 ]
- [ ] [ #4230 ]
- [ ] 反演 [ #4175 ]
- [ ] 欧拉数 [ #4062 ]
- [ ] 特征多项式算法 [ #3758 ]
- [ ] [ #4850 ]
- [ ] [ #5572 ]
- [ ] [ #5492 ]

##### 数据结构

- [ ] [ #4857 ]
- [x] [ #4719 ]
- [ ] [ #4414 ]
- [ ] [ #4211 ]
- [ ] [ #3695 ]
- [x] [ #5221 ]
- [可持久化数据结构简介 - OI Wiki](https://oi-wiki.org/ds/persistent/)
  - [ ] [可持久化块状数组 - OI Wiki](https://oi-wiki.org/ds/persistent-block-array/) 页面目前空缺
  - [ ] [ #3942 ]
  - [ ] [ #1939 ]
- [x] 树套树 [ #223 ]
- [x] toptree [ #6 ]

##### 图论

- [ ] [ #4215 ]
- [ ] 最大费用可行流 [ #2366 ]
- [ ] 动态图连通性问题 [ #2168 ]
- [x] [ #1929 ]
- [ ] [ #1787 ]
- [ ] 模拟费用流 [ #1421 ]
- [ ] 中国邮递员问题 [ #4873 ]

##### 计算几何

- [ ] 计算几何相关 [ #1023 ]
- [ ] 补充凸包页面内容 [ #3261 ]
- [ ] [ #5647 ]

##### 杂项

> 不太好分类的都放在这了

- [x] [ #4407 ]
- 复杂度平衡 or 根号分治（需要讨论）
  - [ ] [ #4784 ]
  - [ ] [ #4155 ]
- 珂朵莉树/颜色段均摊
  - [ ] [ #4368 ]
  - [ ] [ #3981 ]
- [ ] [ #3905 ]
- [ ] Hackenbush Game [ #3224 ]
- [ ] 完善博弈论页面 [ #1852 ]
- [ ] 多维差分 [ #1709 ]
- [ ] 二次离线莫队&回滚莫队 [ #2188 ]
- [ ] Intrinsics [ #955 ]
- [ ] 递归下降分析 [ #4832 ]

#### 工具软件

- [ ] [ #5036 ]
- [ ] 增加 Code::Blocks 的介绍 [ #4621 ]
- [x] [ #4381 ]
- [x] C++ 标准/编译器相关 [ #886 ]
- [x] 编辑器页面表述 [ #698 ]

#### 学习指导

- [ ] OI 专有名词 [ #2753 ]
- [ ] 学习指南 [ #4514 ]
- [ ] 各阶段知识点建议 [ #890 ]
- [ ] Math roadmap [ #2812 ]

### 内容无关的bug

- [x] [ #4771 ]
- [ ] [ #4584 ]
- [ ] [ #1816 ]
- [ ] [ #2312 ]

---

### 内容增强

- [ ] [ #4429 ]
- [ ] [ #4350 ]
- [ ] [ #4243 ]
  - [ #4321 ] 标签页切换功能是否需要在格式手册中叙述一下使用方法
- [ ] [ #3815 ]
- [ ] 对常用数据结构增加动画演示的功能 [ #3221 ]

---

### 长期类

- 对现有页面进行规范 [ #5045 ]
- e-maxx 翻译搬运 [ #148 ]

  > [@Ir1d](https://github.com/Ir1d) 的话：
  > e-maxx 的页面较多，但是每个页面工作量不是很大，欢迎感兴趣的同学认领一下力所能及的部分
  >
  > 有的页面质量不高，也可以留言标注一下跳过 ❤️
  >
  > 请您勇敢地去翻译和改进翻译。虽然我们追求卓越，但我们并不要求您做到十全十美，也请不要担心翻译上犯错——在大部分情况下，git 会记录所有的翻译，因此您不必担心您的失误造成无法挽回的破坏。

- 更换框架 [ #1956 ]
- 英文翻译 [ #1899 ]
- 代码示例问题收集 [ #3196 ]

### 需要讨论/更新进展

> 这部分会涉及各方面内容，目前还没有一个结论，可能需要进一步讨论

- [ ] PR中使用Draft标签代替WIP标签  [ #4672 ]
- [ ] [ #2235 ]
- [x] [ #4613 ]
- [ ] [ #4369 ]
- [ ] [ #4346 ]
- [ ] 编辑及审阅规范 changelog [ #3701 ] 
- [x] [ #3061 ]
- [x] [ #1895 ]
- [x] 语言基础 [ #1831 ]
- [ ] [ #1264 ]
- [ ] 技巧分类 [ #995 ] 

---

### 网站建设

> Request for Comments，欢迎发表你的意见

- [ ] 维护者寄语 [ #3649 ] 
- [ ] 题目储存方式 [ #3518 ] 
- [ ] 征集图标 [ #445 ] 

#### 格式相关

> 格式方面可以先由大家讨论出规范，然后完善格式手册

- [ ] [ #4779 ]
- LaTeX 公式后不应接句号
  - [ ] [ #4872 ]
  - [ ] [ #4246 ]
- [ ] 语义化标签 [ #3818 ]
  - 算法面试（可能能够通过标签解决） [ #3946 ]
- Clang-Format
  - [ ] [ #4644 ]
  - [ ] Clang-Format 上游 fixes [ #2242 ]
- [ ] 格式化数学公式 [ #3718 ]
- [ ] 格式手册对 APNG 的介绍问题 [ #3573 ]
- 关于数字字符格式
  - [ ] 改用 mathtt 可能可以补充格式手册 [ #4374 ] 
  - [ ] [ #4525 ]
- [ ] [ #2039 ]
- [ ] 加到格式手册 or 找出有问题页面并修正 [ #1628 ]
- [ ] SVG 节点和边的 stylesheet [ #3443 ]
- [ ] 统一内容格式，用词称呼等 [ #178 ] 

#### 网站搜索

- 搜索的bug
  - [ ] [ #4762 ]
  - [ ] [ #4494 ]
  - [ ] [ #3664 ]
  - [ ] 或许应该优先 full match [ #3098 ]
- [ ] 拼音搜索功能 [ #3145 ]

---

### 其他
...

**Comment by 0zu-cc** [comment]
> # Iteration Plan
> 
> > 对目前issue进行了分类，欢迎大家搞搞自己擅长的😚
> > 有问题或新进度可以直接修改本issue。
> 
> ## Pull Requests
> 
> > 在统计的过程中发现有些pr开了之后作者没有持续跟进，最后废弃...这部分可以考虑统计下用作后续参考？
> > 这部分没有全罗列上来。
> 
>     * [ ]  根号分治 ([feat(sqrtdivide.md)：新增根号分治的介绍 #5012](https://github.com/OI-wiki/OI-wiki/pull/5012))
> 
> 
> ## Issues
> 
> > 以下是作者/读者请求添加的内容，目前大部分 Issue 都没有相关人员持续跟进。
> > 它们许多都被打上了[Content Request / 内容请求](https://github.com/OI-wiki/OI-wiki/labels/Content%20Request%20%2F%20%E5%86%85%E5%AE%B9%E8%AF%B7%E6%B1%82) 的标签，欢迎到现场围观，添加内容和参考资料，或者是催更。
> > 欢迎持续更新这部分内容，并讨论删除不适合OI-Wiki引入的页面，依据[OI Wiki 不是什么](https://oi-wiki.org/intro/what-oi-wiki-is-not/)。
> 
> ### 不知道放哪
> 
>     * [ ]  中国邮递员问题 ([Add 中国邮递员问题 #4873](https://github.com/OI-wiki/OI-wiki/issues/4873))
> 
>     * [ ]  递归下降分析 ([Add Recursive Descent Parsing #4832](https://github.com/OI-wiki/OI-wiki/issues/4832))
> 
>     * [ ]  ([[内容有误] F.A.Q:Google Hosts 停止更新|FastGit 挂了 #4675](https://github.com/OI-wiki/OI-wiki/issues/4675))
> 
> 
> ### 内容
> 
> > Inherited from Iteration Plan for Spring 2022
> 
> #### 知识点
> ##### 语言基础
> 
>     * [ ]  ([[内容有误] 关于值类别的叙述有误 #4480](https://github.com/OI-wiki/OI-wiki/issues/4480))
> 
> 
> ##### 算法基础
> 
>     * [ ]  二分查找，有人开过pr然后寄了 ([Add 二分查找的其它形式 #4552](https://github.com/OI-wiki/OI-wiki/issues/4552))
> 
>     * [ ]  高维前缀和 ([[完善] 高维前缀和 SOSDP #4151](https://github.com/OI-wiki/OI-wiki/issues/4151))
> 
> 
> ##### 搜索
> 
>     * [ ]  ([[内容有误] 舞蹈链的图有误 #4827](https://github.com/OI-wiki/OI-wiki/issues/4827))
> 
> 
> ##### dp
> 
>     * [ ]  ([DP 优化分类混乱 #1860](https://github.com/OI-wiki/OI-wiki/issues/1860))
> 
> 
> ##### 字符串
> 
>     * [ ]  ([Add 卡掉自然溢出Hash的方法 #4790](https://github.com/OI-wiki/OI-wiki/issues/4790))
> 
>     * [ ]  ([Add 后缀自动机中的正确性证明补充 #4268](https://github.com/OI-wiki/OI-wiki/issues/4268))
> 
>     * [ ]  ([[BUG] 广义SAM内容有误 #3243](https://github.com/OI-wiki/OI-wiki/issues/3243))
> 
> 
> ##### 数学
> 
>     * [ ]  ([Add 基于转置原理推出的多项式多点求值的算法 #5011](https://github.com/OI-wiki/OI-wiki/issues/5011))
> 
>     * 枚举相关，好像duplicated
>       
>       * [ ]  ([Add 枚举子集 / 子集的子集 #5097](https://github.com/OI-wiki/OI-wiki/issues/5097))
>       * [ ]  ([Add 子集枚举 & 全排列 & 补充其他枚举相关 #4991](https://github.com/OI-wiki/OI-wiki/issues/4991))
> 
>     * [ ]  ([Add 秦九韶算法/霍纳法则 #4962](https://github.com/OI-wiki/OI-wiki/issues/4962))
> 
>     * [ ]  ([Add 牛顿恒等式 #4842](https://github.com/OI-wiki/OI-wiki/issues/4842))
> 
>     * [ ]  ([Add 经由变换加速的大数乘法和三模数FNTT #4230](https://github.com/OI-wiki/OI-wiki/issues/4230))
> 
>     * 反演 ([Add 更多反演 #4175](https://github.com/OI-wiki/OI-wiki/issues/4175))
>       
>       * [ ]  [欧拉反演](https://www.cnblogs.com/Morning-Glory/p/11106828.html)
>       * [ ]  [斯特林反演](https://cmwqf.github.io/2020/05/06/%E6%B5%85%E8%B0%88%E6%96%AF%E7%89%B9%E6%9E%97%E5%8F%8D%E6%BC%94/)
>       * [ ]  [拉格朗日反演](https://www.cnblogs.com/chasedeath/p/14421599.html)
>       * [ ]  [莫比乌斯反演 - OI wiki](https://oi-wiki.org/math/number-theory/mobius/)
>       * [ ]  [某炫酷反演魔术](https://vfleaking.blog.uoj.ac/slide/87#/)
> 
>     * [ ]  欧拉数 ([Add 欧拉数（E_n）以及相关内容 #4062](https://github.com/OI-wiki/OI-wiki/issues/4062))
> 
>     * [ ]  特征多项式算法 ([Add alternative charpoly #3758](https://github.com/OI-wiki/OI-wiki/issues/3758))
> 
>     * [ ]  ([add (math) roadmap #2812](https://github.com/OI-wiki/OI-wiki/issues/2812))
> 
> 
> ##### 数据结构
> 
>     * [ ]  ([Add 败者树 #4857](https://github.com/OI-wiki/OI-wiki/issues/4857))
> 
>     * [ ]  ([Add 添加非递归线段树的实现 #4719](https://github.com/OI-wiki/OI-wiki/issues/4719))
> 
>     * [ ]  ([[内容有误] 替罪羊树的实现中重构过于频繁 #4414](https://github.com/OI-wiki/OI-wiki/issues/4414))
> 
>     * [ ]  ([Add 权值线段树介绍 #4211](https://github.com/OI-wiki/OI-wiki/issues/4211))
> 
>     * [ ]  ([Add Link Cut Tree 时间复杂度分析 #3695](https://github.com/OI-wiki/OI-wiki/issues/3695))
> 
>     * [可持久化数据结构简介 - OI Wiki](https://oi-wiki.org/ds/persistent/)
>       
>       * [ ]  [可持久化块状数组 - OI Wiki](https://oi-wiki.org/ds/persistent-block-array/) 页面目前空缺
>         
>         * [ ]  ([[内容补充] 系统介绍数据结构可持久化 #3942](https://github.com/OI-wiki/OI-wiki/issues/3942))
>         * [ ]  ([Add 可持久化動機、堆疊、佇列、雙向佇列、陣列 #1939](https://github.com/OI-wiki/OI-wiki/issues/1939))
> 
>     * [ ]  ([add 树套树 #223](https://github.com/OI-wiki/OI-wiki/issues/223))
> 
> 
> ##### 图
> 
>     * [ ]  ([Add DAG剖分 #4215](https://github.com/OI-wiki/OI-wiki/issues/4215))
> 
>     * [ ]  最大费用可行流 ([add 最大费用可行流 #2366](https://github.com/OI-wiki/OI-wiki/issues/2366))
> 
>     * [ ]  动态图连通性问题 ([add 动态图连通性问题 #2168](https://github.com/OI-wiki/OI-wiki/issues/2168))
> 
>     * [ ]  ([上下界网络流页面待修整 #1929](https://github.com/OI-wiki/OI-wiki/issues/1929))
> 
>     * [ ]  ([关于 LCA 中的标准 RMQ #1787](https://github.com/OI-wiki/OI-wiki/issues/1787))
> 
>     * [ ]  模拟费用流 ([add 模拟费用流 #1421](https://github.com/OI-wiki/OI-wiki/issues/1421))
> 
>     * 树套树 ([add 树套树 #223](https://github.com/OI-wiki/OI-wiki/issues/223))
>       
>       * [ ]  树状数组套树状数组
>       * [ ]  树状数组套线段树
> 
>     * [ ]  toptree ([添加 rbt，B树，leafy tree，toptree #6](https://github.com/OI-wiki/OI-wiki/issues/6))
> 
> 
> ##### 计算几何
> 
>     * [ ]  计算几何相关 ([计算几何, add quaternion, voronoi, fortune算法? #1023](https://github.com/OI-wiki/OI-wiki/issues/1023))
> 
> 
> ##### 杂项
> 
> > 不太好分类的都放在这了
> 
>     * [ ]  ([Add 拟阵 #4850](https://github.com/OI-wiki/OI-wiki/issues/4850))
> 
>     * [x]  ([[内容有误] 离线算法中的普通莫队算法模板代码出错 #4407](https://github.com/OI-wiki/OI-wiki/issues/4407))
> 
>     * 复杂度平衡 or 根号分治（需要讨论）
>       
>       * [ ]  ([Add 根号分治相关内容 #4784](https://github.com/OI-wiki/OI-wiki/issues/4784))
>       * [ ]  ([Add 复杂度平衡 #4155](https://github.com/OI-wiki/OI-wiki/issues/4155))
> 
>     * 珂朵莉树/颜色段均摊
>       
>       * [ ]  ([Add odt map实现 #4368](https://github.com/OI-wiki/OI-wiki/issues/4368))
>       * [ ]  ([[内容有误] 珂朵莉树代码含义不明 #3981](https://github.com/OI-wiki/OI-wiki/issues/3981))
> 
>     * [ ]  ([[功能请求] 能否做一个关于证明算法题目复杂度的系列 #3905](https://github.com/OI-wiki/OI-wiki/issues/3905))
> 
>     * [ ]  Hackenbush Game ( [add Hackenbush Game #3224](https://github.com/OI-wiki/OI-wiki/issues/3224) )
> 
>     * [ ]  完善博弈论页面 ( [博弈论一些概念的区分 #1852](https://github.com/OI-wiki/OI-wiki/issues/1852) )
> 
>     * [ ]  多维差分 ( [add 多维差分 #1709](https://github.com/OI-wiki/OI-wiki/issues/1709) )
> 
>     * [ ]  Math roadmap ( [add (math) roadmap #2812](https://github.com/OI-wiki/OI-wiki/issues/2812) )
> 
>     * [ ]  二次离线莫队&回滚莫队 ( [add 二次离线莫队和在线莫队 #2188](https://github.com/OI-wiki/OI-wiki/issues/2188) )
> 
>     * [ ]  补充凸包页面内容 ( [add 凸包页面内容添加 #3261](https://github.com/OI-wiki/OI-wiki/issues/3261) )
> 
>     * [ ]  Intrinsics ( [add instruction_set(指令集操作相关) #955](https://github.com/OI-wiki/OI-wiki/issues/955) )
> 
> 
> #### 工具软件
> 
>     * [ ]  ([[RFC] 建议规范工具软件的定义，并对 /tools 下的页面进行翻新 #5036](https://github.com/OI-wiki/OI-wiki/issues/5036))
> 
>     * [ ]  增加Code::Blocks的介绍 ([Add Code::Blocks #4621](https://github.com/OI-wiki/OI-wiki/issues/4621))
> 
>     * [ ]  ([Add Windows 和 mac 上 CLion 的工具链配置 #4381](https://github.com/OI-wiki/OI-wiki/issues/4381))
> 
>     * [ ]  Codeforces Contest Helper ([在 OJ 工具页面中添加 Codeforces Contest Helper v2  #4005](https://github.com/OI-wiki/OI-wiki/issues/4005))
> 
>     * [ ]  C++ 标准/编译器相关 ( [add C++ 标准/编译器相关内容 #886](https://github.com/OI-wiki/OI-wiki/issues/886) )
> 
>     * [ ]  编辑器页面表述 ( [建议修改「编辑工具」一页中的表述 #698](https://github.com/OI-wiki/OI-wiki/issues/698) )
> 
> 
> #### 学习指导
> 
>     * [ ]  OI专有名词 ([Add OI专有名词 #2753](https://github.com/OI-wiki/OI-wiki/issues/2753))
> 
>     * [ ]  学习指南 ([Add 学习指南 [WIP] #4514](https://github.com/OI-wiki/OI-wiki/issues/4514))
> 
>     * [ ]  各阶段知识点建议 ([add 各阶段知识点建议 #890](https://github.com/OI-wiki/OI-wiki/issues/890))
> 
> 
> ### 内容无关的bug
> 
>     * [x]  ([[BUG] 移动欧拉函数 #4771](https://github.com/OI-wiki/OI-wiki/issues/4771))
> 
>     * [ ]  ([[BUG] Mathjax 渲染得过于紧凑 #4584](https://github.com/OI-wiki/OI-wiki/issues/4584))
> 
>     * [ ]  ([编辑前提醒阅读 htc 页面的链接问题 #1816](https://github.com/OI-wiki/OI-wiki/issues/1816))
> 
>     * [ ]  ([[BUG] bot 在处理 Markdown 时的问题 #2312](https://github.com/OI-wiki/OI-wiki/issues/2312))
> 
> 
> ### 内容增强
> 
>     * [ ]  ([[功能请求] Java 代码的格式化配置 #4429](https://github.com/OI-wiki/OI-wiki/issues/4429))
> 
>     * [ ]  ([[功能请求] Python 例题代码自动检查 #4350](https://github.com/OI-wiki/OI-wiki/issues/4350))
> 
>     * [ ]  ([[功能请求] 代码实现示例中增加Java示例 #4243](https://github.com/OI-wiki/OI-wiki/issues/4243))
>       
>       * [#4321](https://github.com/OI-wiki/OI-wiki/issues/4321)标签页切换功能是否需要在格式手册中叙述一下使用方法
> 
>     * [ ]  ([[功能请求] 请求添加折叠侧栏的功能 #3815](https://github.com/OI-wiki/OI-wiki/issues/3815))
> 
>     * [ ]  对常用数据结构增加动画演示的功能 ([希望对常用数据结构增加动画演示的功能 #3221](https://github.com/OI-wiki/OI-wiki/issues/3221))
> 
> 
> ### 长期类
> 
>     * 对现有页面进行规范 ([[RFC] 根据「OI Wiki 不是什么」征集需要修改的页面列表 #5045](https://github.com/OI-wiki/OI-wiki/issues/5045))
> 
>     * e-maxx 翻译搬运 ([关于 e-maxx 的进度 #148](https://github.com/OI-wiki/OI-wiki/issues/148))
> 
> 
> > [@Ir1d](https://github.com/Ir1d) 的话：
> > e-maxx 的页面较多，但是每个页面工作量不是很大，欢迎感兴趣的同学认领一下力所能及的部分
> > 有的页面质量不高，也可以留言标注一下跳过 ❤️
> > 请您勇敢地去翻译和改进翻译。虽然我们追求卓越，但我们并不要求您做到十全十美，也请不要担心翻译上犯错——在大部分情况下，git 会记录所有的翻译，因此您不必担心您的失误造成无法挽回的破坏。
> 
>     * 更换框架 ([关于更换框架的事宜 #1956](https://github.com/OI-wiki/OI-wiki/issues/1956))
> 
>     * 英文翻译 ([提供英文翻译 #1899](https://github.com/OI-wiki/OI-wiki/issues/1899))
> 
> 
> ### 需要讨论/更新进展
> 
> > 这部分会涉及各方面内容，目前还没有一个结论，可能需要进一步讨论
> 
>     * [ ]  PR中使用Draft标签代替WIP标签  ([[BUG][RFC] 移除 WIP 标签 #4672](https://github.com/OI-wiki/OI-wiki/issues/4672))
> 
>     * [ ]  ([在 pr 被合并后移除“等待审核”标签 #2235](https://github.com/OI-wiki/OI-wiki/issues/2235))
> 
>     * [ ]  ([[建议 Suggestions / Bugs]  GitHub Actions 对未修改内容仍执行 Check #4613](https://github.com/OI-wiki/OI-wiki/issues/4613))
> 
>     * [ ]  ([关于 Leafy tree 的讨论 #4369](https://github.com/OI-wiki/OI-wiki/issues/4369))
> 
>     * [ ]  ([[RFC] 针对打印版的无障碍阅读改进 #4346](https://github.com/OI-wiki/OI-wiki/issues/4346))
> 
>     * [ ]  有小朋友用，保留 ([Add AtCoder Library Tutorial #3893](https://github.com/OI-wiki/OI-wiki/issues/3893))
> 
>     * [ ]  编辑及审阅规范 changelog ([[RFC] 添加一份 OI Wiki 的编辑及审阅规范的变迁记录 #3701](https://github.com/OI-wiki/OI-wiki/issues/3701))
> 
>     * [ ]  ([[内容修正] 格式手册中关于 APNG 更详细的指导 #3573](https://github.com/OI-wiki/OI-wiki/issues/3573))
> 
>     * [ ]  ([[RFC] 关于SVG的图形格式的讨论 #3443](https://github.com/OI-wiki/OI-wiki/issues/3443))
> 
>     * [ ]  ([add 代码示例问题的收集 #3196](https://github.com/OI-wiki/OI-wiki/issues/3196))
> 
>     * [ ]  ([[RFC] 关于 Commit Message 书写以及 PR 合并方式的问题 #3061](https://github.com/OI-wiki/OI-wiki/issues/3061))
> 
>     * [x]  ([建议在新标签页打开站外链接 #1895](https://github.com/OI-wiki/OI-wiki/issues/1895))
> 
>     * [ ]  语言基础 ([fix: 语言基础的许多问题和内容缺失 #1831](https://github.com/OI-wiki/OI-wiki/issues/1831))
> 
>     * [ ]  ([考虑每个例题单独一个页面 #1264](https://github.com/OI-wiki/OI-wiki/issues/1264))
> 
>     * [ ]  技巧分类 ([关于给杂项中的技巧进行分类(Brain Storm) #995](https://github.com/OI-wiki/OI-wiki/issues/995))
> 
> 
> ### 网站建设
> 
> > Request for Comments，欢迎发表你的意见
> 
>     * [ ]  维护者寄语 ([[RFC] Add 类似“维护者寄语/前言”的页面 #3649](https://github.com/OI-wiki/OI-wiki/issues/3649))
> 
>     * [ ]  题目储存方式 ([[RFC] 关于统一题目存储方式的讨论 #3518](https://github.com/OI-wiki/OI-wiki/issues/3518))
> 
>     * [ ]  征集图标 ([征集图标 #445](https://github.com/OI-wiki/OI-wiki/issues/445))
> 
> 
> #### 格式相关
> 
> > 格式方面可以先由大家讨论出规范，然后完善格式手册
> 
>     * [ ]  ([[功能请求] 禁止在正文中使用斜体中文 #4779](https://github.com/OI-wiki/OI-wiki/issues/4779))
> 
>     * LaTeX 公式后不应接句号
>       
>       * [ ]  ([[RFC] LaTeX 公式后不应接句号「。」 #4872](https://github.com/OI-wiki/OI-wiki/issues/4872))
>       * [ ]  ([[¿not bug] Chinese punctuation after latin and number is not a good practice #4246](https://github.com/OI-wiki/OI-wiki/issues/4246))
> 
>     * [ ]  语义化标签 ([[Proposal] OI Wiki Semantic Label for Paragraph #3818](https://github.com/OI-wiki/OI-wiki/issues/3818))
>       
>       * 算法面试（可能能够通过标签解决） ([[proposal] OI Wiki for algorithm interview #3946](https://github.com/OI-wiki/OI-wiki/issues/3946))
> 
>     * Clang-Format
>       
>       * [ ]  ([多语言的 code block 无法被 remark 识别以及使用 clang-format 进行格式化 #4644](https://github.com/OI-wiki/OI-wiki/issues/4644))
>       * [ ]  Clang-Format 上游 fixes ([clang-format 配置需调整 #2242](https://github.com/OI-wiki/OI-wiki/issues/2242))
> 
>     * [ ]  格式化数学公式 ([格式化 Markdown 文件时将数学公式一并格式化 #3718](https://github.com/OI-wiki/OI-wiki/issues/3718))
> 
>     * [ ]  格式手册对 APNG 的介绍问题 ([[内容修正] 格式手册中关于 APNG 更详细的指导 #3573](https://github.com/OI-wiki/OI-wiki/issues/3573))
> 
>     * 关于数字字符格式
>       
>       * [ ]  改用 mathtt可能可以补充格式手册 ([关于部分公式字符改为 mathtt 的讨论 #4374](https://github.com/OI-wiki/OI-wiki/issues/4374))
>       * [ ]  ([如何处理数学公式中的多字母变量？ #4525](https://github.com/OI-wiki/OI-wiki/issues/4525))
> 
>     * [ ]  ([给例题配个能交的 link #2039](https://github.com/OI-wiki/OI-wiki/issues/2039))
> 
>     * [ ]  加到格式手册 or 找出有问题页面并修正 ([区分 参考资料 和 拓展阅读 #1628](https://github.com/OI-wiki/OI-wiki/issues/1628))
> 
>     * [ ]  SVG 节点和边的 stylesheet ( ([[RFC] 关于SVG的图形格式的讨论 #3443](https://github.com/OI-wiki/OI-wiki/issues/3443)) )
> 
>     * [ ]  统一内容格式，用词称呼等 ([考虑统一内容格式 #178](https://github.com/OI-wiki/OI-wiki/issues/178))
> 
> 
> #### 网站搜索
> 
>     * 搜索的bug
>       
>       * [ ]  ([[BUG] 无法搜索出A* #4762](https://github.com/OI-wiki/OI-wiki/issues/4762))
>       * [ ]  ([[BUG] 对内容的搜索问题 #4494](https://github.com/OI-wiki/OI-wiki/issues/4494))
>       * [ ]  ([[BUG] 搜索的一些问题 #3664](https://github.com/OI-wiki/OI-wiki/issues/3664))
>       * [ ]  或许应该优先full match ([搜索“折半搜索”，列表第七个才是二分 #3098](https://github.com/OI-wiki/OI-wiki/issues/3098))
> 
>     * [ ]  拼音搜索功能 ([add 拼音搜索 #3145](https://github.com/OI-wiki/OI-wiki/issues/3145))
> 
> 
> ### 其他
> 
> ...

置顶一下？

**Comment by Great-designer** [comment]
已经断掉的pr可以考虑重新链接到原有的issue

**Comment by Great-designer** [comment]
已经2024年了，一年过去。

更新下标题，还是另开一个新的？

**Comment by Tiphereth-A** [comment]
close via #5698
