### ISSUE TITLE
抽象代数相关页面完善计划

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#5356]
目前 OI Wiki 已有一些抽象代数的内容，如 [群论简介](https://oi-wiki.org/math/group-theory/) 与 [置换群](https://oi-wiki.org/math/permutation-group/)，也有对一些具体代数结构的介绍，如 [一元多项式环与形式幂级数环](https://oi-wiki.org/math/poly/intro/)、[二次域](https://oi-wiki.org/math/number-theory/quadratic/)。这些内容目前有如下问题：

1. 内容组织不合逻辑。如群论简介页面中先定义群后定义半群与幺半群，且半群、幺半群被视为了群的衍生结构。
2. 内容分布零散。如群论简介和二次域页面中都有部分环论内容，这些内容应该被统合进一个页面中。
3. 缺乏基础概念。如二次域页面中介绍了主理想整环，但并没有介绍理想的相关概念。

所以我认为目前 OI Wiki 需要完善部分抽象代数相关内容的介绍，但是抽象代数对于 OI 来说可能较为艰深晦涩，所以不宜引入过多内容，且应更多侧重于对具体例子的分析。

我认为需要完善的具体内容如下：

- [x] 群论：有限 Abel 群分类定理、群的三大同构定理、群作用、轨道和稳定化子、中心化子和正规化子 (#5974)
- [x] 环论：环简介、理想、商环 (#5984)
- [ ] 域论：域简介、有限域、域扩张 (#5913)

由于本人对抽象代数在算法竞赛中的应用程度不够熟悉，所以列表里可能有缺失和多余的内容，欢迎大家批评指正 :heart:

**Comment by Great-designer** [comment]
我认为这有些太多了。

但是把现有的内容按概念拆分成不同的页面，并整合到同一个目录下，还是比较重要的。

另外，“代数系统”这个概念先于群，诸如偏序集/狄尔沃斯定理等等，应当率先简要介绍。还有，“线性空间”是一种特殊的代数结构，似乎应当放在后面。

**Comment by Great-designer** [comment]
另外，有限自动机如DFA/NFA等，也与代数系统密切相关，而各类有限自动机是形式语言、编程语言的基础，至少可以应用在编译技术与字符串处理上。上述内容参见尹宝林版《离散数学》最后一章。感兴趣的话可以作为这部分最后的内容。

**Comment by Tiphereth-A** [comment]
> 还有，“线性空间”是一种特殊的代数结构，似乎应当放在后面。

我觉得应该没必要介绍模，所以线性空间维持原状就好

**Comment by Tiphereth-A** [comment]
> 我认为这有些太多了。

不知您认为目前列表里哪些是没有必要的，我认为至少群论和环论里列出来的部分都是较为基础且重要的概念，而且目前在 OI Wiki 这边也已经得到了一定程度的应用。

> 另外，“代数系统”这个概念先于群，诸如偏序集/狄尔沃斯定理等等，应当率先简要介绍。

这是序理论的内容，不在本 issue 讨论的范围内。

**Comment by OIer1048576** [comment]
加一些有限 Abel 群分类定理?

**Comment by OIer1048576** [comment]
线性代数内容应该也要大修。

**Comment by Great-designer** [comment]
> 不知您认为目前列表里哪些是没有必要的，我认为至少群论和环论里列出来的部分都是较为基础且重要的概念，而且目前在 OI Wiki 这边也已经得到了一定程度的应用。

印象里老早以前你的初稿应该已经可以了。（虽然初稿似乎删了）

**Comment by Great-designer** [comment]
> 线性代数内容应该也要大修。

这个得有人有时间愿意修才行。

**Comment by Tiphereth-A** [comment]
> 加一些有限 Abel 群分类定理?

added

**Comment by Tiphereth-A** [comment]
> 印象里老早以前你的初稿应该已经可以了。（虽然初稿似乎删了）

那个我记得主要都是集合论的东西 🤔

**Comment by Great-designer** [comment]
> 那个我记得主要都是集合论的东西 🤔

我认为可以。从集合论出发，和从代数系统出发也差不多。我最早学的时候看的离散数学版本是从代数系统那儿开始讲的。能找到前置概念就行。

**Comment by Tiphereth-A** [comment]
> > 那个我记得主要都是集合论的东西 🤔
> 
> 我认为可以。从集合论出发，和从代数系统出发也差不多。我最早学的时候看的离散数学版本是从代数系统那儿开始讲的。能找到前置概念就行。

我的意思是你 off topic 了，集合论的内容插个外链就好了，没必要引过来。我删了那个稿子的其中一个原因就是这个。

**Comment by Great-designer** [comment]
环里面得介绍一下环的进阶内容。大家并不会只研究一个普通的环，往往会研究：

· 幺环：含有乘法单位元的环
· 交换环：乘法运算可交换的环
· 无零因子环：封闭的环
- 整环：上述三者的结合。数论里面常见研究对象。
- 体：乘法运算构成群，即封闭、含有乘法单位元、每个元素都有逆元。例如四元数体。（四元数和三维旋转有机会也可以讲讲，据说编程实现三维旋转的技术常用四元数）
- 域：可交换的体。

参见：https://zhuanlan.zhihu.com/p/53621008

这部分书写的必要性，是因为在数论部分的最后几个页面，研究的都是整环，而非一般的环。里面讲了很多单纯属于整环的内容，事实上可以挪出来。
