### ISSUE TITLE
Iteration Plan for 2024

### ISSUE THREAD

**Issue by Tiphereth-A** [OI-wiki/OI-wiki#5698]
# Iteration Plan for 2024

~~季度计划似乎已经咕成年度计划了~~

![image](https://user-images.githubusercontent.com/30773956/107211760-f5d8a800-6a40-11eb-82a3-d34ff3957883.png)

![image](https://user-images.githubusercontent.com/30773956/64026172-cdbcf800-cb70-11e9-8ec9-edd9d6ca4cde.png)

## Changelog

Initial version by @Tiphereth-A on 2024/07/05

## For beginners

> 如果您是第一次参与本项目，推荐优先考虑打了 [good first issue / 对新手友好](https://github.com/OI-wiki/OI-wiki/labels/good%20first%20issue%20%2F%20%E5%AF%B9%E6%96%B0%E6%89%8B%E5%8F%8B%E5%A5%BD) 标签的 Issue，这些 Issue 往往是简单的内容请求，抑或是简单的长期工作，解决这些 Issue 能够帮助您快速了解该项目。

## RFCs

> 以下是作者/读者提交的关于改进站点的提案。
>
> 它们都被打上了 [RFC / 提案](https://github.com/OI-wiki/OI-wiki/labels/RFC%20%2F%20%E6%8F%90%E6%A1%88) 的标签，欢迎前往现场发表观点与意见。

### 站点与仓库维护

- [x] [ #4672 ]
- [x] [ #3701 ]
- [ ] [ #3518 ]

### 格式

- [ ] [ #4872 ]
  related [ #4246 ]
- [ ] [ #4525 ]

- [ ] [ #3443 ]

### 页面重构

- [ ] [ #5327 ]
- [ ] [ #5036 ]

### 内容增强

- [ ] [ #4346 ]
- [ ] [ #3946 ]
- [ ] [ #3818 ]

### 杂项

- [x] [ #4196 ]
- [ ] [ #3649 ]

## Issues

> 以下是作者/读者请求添加的内容，目前大部分 Issue 都没有相关人员持续跟进。
>
> 它们许多都被打上了 [Content Request / 内容请求](https://github.com/OI-wiki/OI-wiki/labels/Content%20Request%20%2F%20%E5%86%85%E5%AE%B9%E8%AF%B7%E6%B1%82) 的标签，欢迎到现场围观，添加内容和参考资料，或者是催更。
>
> 欢迎持续更新这部分内容，或依据 [OI Wiki 不是什么](https://oi-wiki.org/intro/what-oi-wiki-is-not/) 删除不适合引入的内容。

### 内容

> Inherited from Iteration Plan for 2023

##### 语言基础

- [x] [ #4480 ]

##### 算法基础

- [x] [ #5536 ]
- [ ] 二分查找，有人开过 PR 但是寄了 [ #4552 ]
- [x] 高维前缀和 [ #4151 ]
- [x] 多维差分 [ #1709 ]

##### 搜索

- [x] [ #5444 ]
- [x] [ #5394 ]

##### DP

- [x] [ #5379 ]
- [x] [ #5363 ]
- [x] [ #1860 ]
- [x] [ #6247 ]

##### 字符串

- [x] [ #4790 ]
- [x] [ #4268 ]
- [ ] [ #3243 ]

##### 数学

- [x] [ #5572 ]
- [x] [ #5492 ]
- [x] [ #5356 ]
- [ ] [ #5011 ]
- [x] [ #4850 ]
- [ ] [ #4842 ]
- [ ] [ #4230 ]
- [ ] [ #4175 ]
- [ ] [ #4062 ]
- [ ] 特征多项式算法 [ #3758 ]
- [ ] [ #6440 ]

##### 数据结构

- [x] [ #4857 ]
- [x] [ #4414 ]
- [ ] [ #4211 ]
- [x] [ #3695 ]
- 可持久化数据结构
  - [ ] [可持久化块状数组](https://oi-wiki.org/ds/persistent-block-array/) 页面目前空缺
  - [ ] [ #3942 ]
  - [ ] [ #1939 ]
- [x] [ #5709 ]
- [ ] [ #5795 ]
- [x] [ #6137 ]

##### 图论

- [x] [ #5661 ]
- [ ] [ #4873 ]
- [ ] [ #4215 ]
- [ ] [ #2168 ]
- [x] [ #1787 ]
- [ ] [ #1421 ]
- [x] [ #6135 ]
- [ ] [ #6470 ]

##### 计算几何

- [x] [ #5647 ]
- [ ] [ #5637 ]
- [ ] [ #3261 ]
- [ ] [ #1023 ]

##### 博弈论

- [x] 完善博弈论页面 [ #1852 ]

##### 魔法

- [x] Intrinsics [ #955 ]

##### 杂项

- [ ] [ #5680 ]
- [x] [ #5434 ]
- [ ] 递归下降分析 [ #4832 ]
- [ ] [ #3905 ]
- [x] [ #2188 ]
- 复杂度平衡/根号分治（需要讨论）
  - [ ] [ #4784 ]
  - [ ] [ #4155 ]
- 珂朵莉树/颜色段均摊
  - [x] [ #4368 ]
  - [x] [ #3981 ]
- [ ] [ #6368 ]

#### 工具软件

- [x] [ #4621 ]

#### 学习指导

- [ ] 学习指南 [ #4514 ]
- [ ] Math roadmap [ #2812 ]
- [ ] OI 专有名词 [ #2753 ]
- [ ] 各阶段知识点建议 [ #890 ]

---

### 内容无关的 bug

- [x] [ #5690 ]
- [x] [ #5587 ]
- [ ] [ #5745 ]
- [ ] [ #5288 ]
- [ ] [ #4584 ]
- [x] [ #2312 ]
- [ ] [ #1816 ]

### 内容增强

- [ ] [ #5287 ]
- [ ] [ #4350 ]
- [ ] [ #4243 ]
- [x] [ #3815 ]
- [ ] [ #3221 ]

---

### 长期类

- 对现有页面进行规范 [ #5045 ]
- 代码示例问题收集 [ #3196 ]
- 英文翻译 [ #1899 ]
- e-maxx 翻译搬运 [ #148 ]

  > @Ir1d 的话：
  > e-maxx 的页面较多，但是每个页面工作量不是很大，欢迎感兴趣的同学认领一下力所能及的部分
  >
  > 有的页面质量不高，也可以留言标注一下跳过 ❤️
  >
  > 请您勇敢地去翻译和改进翻译。虽然我们追求卓越，但我们并不要求您做到十全十美，也请不要担心翻译上犯错——在大部分情况下，git 会记录所有的翻译，因此您不必担心您的失误造成无法挽回的破坏。

### 需要讨论/更新进展

> 这部分会涉及各方面内容，目前还没有一个结论，可能需要进一步讨论

- [ ] [ #5670 ]
- [x] [ #4369 ]
- [ ] [ #2235 ]
- [ ] [ #1264 ]
- [ ] 技巧分类 [ #995 ] 

---

### 网站建设

> Request for Comments，欢迎发表你的意见

- [ ] 征集图标 [ #445 ] 

#### 格式相关

> 格式方面可以先由大家讨论出规范，然后完善格式手册

- [ ] [ #4779 ]
- [ ] 格式化数学公式 [ #3718 ]
- [ ] 格式手册对 APNG 的介绍问题 [ #3573 ]
- [ ] [ #2039 ]
- [ ] 加到格式手册 or 找出有问题页面并修正 [ #1628 ]
- [ ] 统一内容格式，用词称呼等 [ #178 ] 
- Clang-Format
  - [ ] [ #4644 ]
  - [ ] [ #4429 ]
  - [x] Clang-Format 上游 fixes [ #2242 ]

#### 网站搜索

- [x] 拼音搜索功能 [ #3145 ]
- 搜索的 bug
  - [ ] [ #4762 ]
  - [x] [ #4494 ]
  - [x] [ #3664 ]
  - [ ] 或许应该优先 full match [ #3098 ]
  - [x] [ #5689 ]

---

### 其他
...

**Comment by c-forrest** [comment]
closed via #6471
